### ISSUE TITLE
Line 154

### ISSUE THREAD

**Issue by matikin9** [LACMTA/mybus#57]
@EbbyEbby The stop changes data we have for Line 154 doesn't seem to make sense.  Can you have the service planners confirm?

![image](https://user-images.githubusercontent.com/1873072/131926420-677ce4dd-281a-4000-8d7d-e376443366fc.png)
![image](https://user-images.githubusercontent.com/1873072/131926452-d513332f-fc5b-45d1-9120-d1a37c3b60f1.png)

**Comment by EbbyEbby** [comment]
@matikin9 Per Israel- Line 154 is an anomaly.  Due to the route dipping down to serve North Hollywood Station, it serves Lankershim/Collins twice in each direction even though it is on opposite sides of the street.
 
I think to make it less confusing for patrons, we can keep only one mention of this stop for eastbound, and one mention for westbound.  

![image](https://user-images.githubusercontent.com/89943409/132032023-9cff00e9-a04c-4151-a8b6-665ace40ad6a.png)

**Comment by albertkun** [comment]
I agree with @EbbyEbby !

**Comment by matikin9** [comment]
Task:

- [ ] update the front end to remove duplicate stop name/direction combinations
