### ISSUE TITLE
Line 106 (New update) all summary pages 

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#70]
Met with planners, and there are some last minute changes- fun. In the all summary pages the 106 will need copy altered to this: (the change is second to last sentence about where bus will travel). 

106 – Line 106 will be extended via Marengo St, Mission Rd, Cesar E Chavez Av, Alameda St, Los Angeles St, Temple St and 1st St in order to service downtown LA (Union Station and Little Tokyo). Due to construction, the bus will travel via 1st St between Vignes and Los Angeles Sts until Temple St reopens. Service on State St will be discontinued.   Download new schedule for Line 106.

@matikin9  how to we handle the Spanish and other languages?

**Comment by matikin9** [comment]
**New Line 106 copy:**

106 – Line 106 will be extended via Marengo St, Mission Rd, Cesar E Chavez Av, Alameda St, Los Angeles St, Temple St and 1st St in order to service downtown LA (Union Station and Little Tokyo). Due to construction, the bus will travel via 1st St between Vignes and Los Angeles Sts until Temple St reopens. Service on State St will be discontinued.

- [ ] Update All Changes data (Albert)
- [ ] Update Line Level data (Nina)

**Comment by matikin9** [comment]
@EbbyEbby for translations, we can generate auto-translations for now and you can send us any manual translations if/when you're able to.
