### ISSUE TITLE
Line 30 & 854 All summary page + Line level details 

### ISSUE THREAD

**Issue by EbbyEbby** [LACMTA/mybus#71]
Putting this request together because maybe it can be solved by adding an * but let me now if you think there's a better solution. We also need to update this copy in the details section on appropriate stop. 

30 – Line 30* will be rerouted in late September due to Regional Connector construction in the downtown LA Little Tokyo area via 1st St, Judge John Aiso St, Temple St, Vignes St and 1st St.  Download new schedule for Line 30.
 
854 –  Line 854* Gold Line Bus Bridge will be rerouted due to Regional Connector construction in the downtown LA Little Tokyo area via 1st St, Judge John Aiso St, Temple St, Vignes St and 1st St. Download new schedule for Line 854.
 
*Note: Lines 30 & 854 effective date is delayed and changes will not be taking place on 9/12, please refer back to this site as information will be updated or check for posted signage at the bus stop.  The lines will remain on existing route via 1st St between Los Angeles St and Vignes St.

**Comment by matikin9** [comment]
**Line 30 new copy:**

30 – Line 30 will be rerouted in late September due to Regional Connector construction in the downtown LA Little Tokyo area via 1st St, Judge John Aiso St, Temple St, Vignes St and 1st St.  Note that the effective date is delayed and changes will not be taking place on 9/12, please refer back to this site as information will be updated or check for posted signage at the bus stop. This line will remain on existing route via 1st St between Los Angeles St and Vignes St.

**Line 854 new copy:**

854 – Line 854 Gold Line Bus Bridge will be rerouted due to Regional Connector construction in the downtown LA Little Tokyo area via 1st St, Judge John Aiso St, Temple St, Vignes St and 1st St.  Note that the effective date is delayed and changes will not be taking place on 9/12, please refer back to this site as information will be updated or check for posted signage at the bus stop. This line will remain on existing route via 1st St between Los Angeles St and Vignes St.

**All Changes Page (Albert)**

- [ ] Update the translation doc with Google Translated copy.
- [ ] Generate updated data file.

**Line Level Details (Nina)**

- [ ] Update the Google sheet with the new copy.
- [ ] Generate the updated data file.
